version: '3'
services:
  webapp:
    environment:
      WX_APP_SECRET:
      OPENAI_API_KEY:
      OPENAI_API_BASE:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    command:
      /bin/python3 -m uvicorn main:create_app --host 0.0.0.0 --port 8000
